/*
 * This file is generated by jOOQ.
*/
package com.findit.jooq;


import com.findit.jooq.tables.Email;
import com.findit.jooq.tables.Meetings;
import com.findit.jooq.tables.StudentMeeting;
import com.findit.jooq.tables.Students;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MEETINGS_PKEY = Indexes0.MEETINGS_PKEY;
    public static final Index STUDENT_MEETING_PKEY = Indexes0.STUDENT_MEETING_PKEY;
    public static final Index FKI_FK_MEETING = Indexes0.FKI_FK_MEETING;
    public static final Index FKI_FK_STUDENT = Indexes0.FKI_FK_STUDENT;
    public static final Index STUDENTS_PKEY = Indexes0.STUDENTS_PKEY;
    public static final Index EMAIL_PKEY = Indexes0.EMAIL_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MEETINGS_PKEY = Internal.createIndex("Meetings_pkey", Meetings.MEETINGS, new OrderField[] { Meetings.MEETINGS.MEETING_ID }, true);
        public static Index STUDENT_MEETING_PKEY = Internal.createIndex("Student_Meeting_pkey", StudentMeeting.STUDENT_MEETING, new OrderField[] { StudentMeeting.STUDENT_MEETING.ID }, true);
        public static Index FKI_FK_MEETING = Internal.createIndex("fki_fk_meeting", StudentMeeting.STUDENT_MEETING, new OrderField[] { StudentMeeting.STUDENT_MEETING.MEETING_ID }, false);
        public static Index FKI_FK_STUDENT = Internal.createIndex("fki_fk_student", StudentMeeting.STUDENT_MEETING, new OrderField[] { StudentMeeting.STUDENT_MEETING.STUDENT_ID }, false);
        public static Index STUDENTS_PKEY = Internal.createIndex("Students_pkey", Students.STUDENTS, new OrderField[] { Students.STUDENTS.STUDENT_ID }, true);
        public static Index EMAIL_PKEY = Internal.createIndex("email_pkey", Email.EMAIL, new OrderField[] { Email.EMAIL.ID }, true);
    }
}
