/*
 * This file is generated by jOOQ.
*/
package com.findit.jooq;


import com.findit.jooq.tables.Email;
import com.findit.jooq.tables.Meetings;
import com.findit.jooq.tables.StudentMeeting;
import com.findit.jooq.tables.Students;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 2092709622;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.Meetings</code>.
     */
    public final Meetings MEETINGS = com.findit.jooq.tables.Meetings.MEETINGS;

    /**
     * The table <code>public.Student_Meeting</code>.
     */
    public final StudentMeeting STUDENT_MEETING = com.findit.jooq.tables.StudentMeeting.STUDENT_MEETING;

    /**
     * The table <code>public.Students</code>.
     */
    public final Students STUDENTS = com.findit.jooq.tables.Students.STUDENTS;

    /**
     * The table <code>public.email</code>.
     */
    public final Email EMAIL = com.findit.jooq.tables.Email.EMAIL;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.EMAIL_ID_SEQ,
            Sequences.MEETINGS_MEETING_ID_SEQ,
            Sequences.STUDENT_MEETING_ID_SEQ,
            Sequences.STUDENTS_STUDENT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Meetings.MEETINGS,
            StudentMeeting.STUDENT_MEETING,
            Students.STUDENTS,
            Email.EMAIL);
    }
}
