/*
 * This file is generated by jOOQ.
*/
package com.findit.jooq;


import com.findit.jooq.tables.Email;
import com.findit.jooq.tables.Meetings;
import com.findit.jooq.tables.StudentMeeting;
import com.findit.jooq.tables.Students;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.Meetings</code>.
     */
    public static final Meetings MEETINGS = com.findit.jooq.tables.Meetings.MEETINGS;

    /**
     * The table <code>public.Student_Meeting</code>.
     */
    public static final StudentMeeting STUDENT_MEETING = com.findit.jooq.tables.StudentMeeting.STUDENT_MEETING;

    /**
     * The table <code>public.Students</code>.
     */
    public static final Students STUDENTS = com.findit.jooq.tables.Students.STUDENTS;

    /**
     * The table <code>public.email</code>.
     */
    public static final Email EMAIL = com.findit.jooq.tables.Email.EMAIL;
}
