/*
 * This file is generated by jOOQ.
*/
package com.findit.joog;


import com.findit.joog.tables.Meetings;
import com.findit.joog.tables.MeetingsUser;
import com.findit.joog.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MEETINGS_PKEY = Indexes0.MEETINGS_PKEY;
    public static final Index MEETINGS_USER_PKEY = Indexes0.MEETINGS_USER_PKEY;
    public static final Index FKI_MEETINGS_ID_FK = Indexes0.FKI_MEETINGS_ID_FK;
    public static final Index FKI_USER_ID_FK = Indexes0.FKI_USER_ID_FK;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index MEETINGS_PKEY = createIndex("Meetings_pkey", Meetings.MEETINGS, new OrderField[] { Meetings.MEETINGS.MEETING_ID }, true);
        public static Index MEETINGS_USER_PKEY = createIndex("Meetings_User_pkey", MeetingsUser.MEETINGS_USER, new OrderField[] { MeetingsUser.MEETINGS_USER.ID }, true);
        public static Index FKI_MEETINGS_ID_FK = createIndex("fki_meetings_id_fk", MeetingsUser.MEETINGS_USER, new OrderField[] { MeetingsUser.MEETINGS_USER.MEETING_ID }, false);
        public static Index FKI_USER_ID_FK = createIndex("fki_user_id_fk", MeetingsUser.MEETINGS_USER, new OrderField[] { MeetingsUser.MEETINGS_USER.USER_ID }, false);
        public static Index USER_PKEY = createIndex("User_pkey", User.USER, new OrderField[] { User.USER.USER_ID }, true);
    }
}
