/*
 * This file is generated by jOOQ.
*/
package com.findit.joog;


import com.findit.joog.tables.Meetings;
import com.findit.joog.tables.MeetingsUser;
import com.findit.joog.tables.User;
import com.findit.joog.tables.records.MeetingsRecord;
import com.findit.joog.tables.records.MeetingsUserRecord;
import com.findit.joog.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MeetingsRecord> MEETINGS_PKEY = UniqueKeys0.MEETINGS_PKEY;
    public static final UniqueKey<MeetingsUserRecord> MEETINGS_USER_PKEY = UniqueKeys0.MEETINGS_USER_PKEY;
    public static final UniqueKey<UserRecord> USER_PKEY = UniqueKeys0.USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MeetingsUserRecord, MeetingsRecord> MEETINGS_USER__MEETINGS_ID_FK = ForeignKeys0.MEETINGS_USER__MEETINGS_ID_FK;
    public static final ForeignKey<MeetingsUserRecord, UserRecord> MEETINGS_USER__USER_ID_FK = ForeignKeys0.MEETINGS_USER__USER_ID_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<MeetingsRecord> MEETINGS_PKEY = createUniqueKey(Meetings.MEETINGS, "Meetings_pkey", Meetings.MEETINGS.MEETING_ID);
        public static final UniqueKey<MeetingsUserRecord> MEETINGS_USER_PKEY = createUniqueKey(MeetingsUser.MEETINGS_USER, "Meetings_User_pkey", MeetingsUser.MEETINGS_USER.ID);
        public static final UniqueKey<UserRecord> USER_PKEY = createUniqueKey(User.USER, "User_pkey", User.USER.USER_ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<MeetingsUserRecord, MeetingsRecord> MEETINGS_USER__MEETINGS_ID_FK = createForeignKey(com.findit.joog.Keys.MEETINGS_PKEY, MeetingsUser.MEETINGS_USER, "Meetings_User__meetings_id_fk", MeetingsUser.MEETINGS_USER.MEETING_ID);
        public static final ForeignKey<MeetingsUserRecord, UserRecord> MEETINGS_USER__USER_ID_FK = createForeignKey(com.findit.joog.Keys.USER_PKEY, MeetingsUser.MEETINGS_USER, "Meetings_User__user_id_fk", MeetingsUser.MEETINGS_USER.USER_ID);
    }
}
