/*
 * This file is generated by jOOQ.
*/
package com.findit.joog;


import com.findit.joog.tables.Meetings;
import com.findit.joog.tables.MeetingsUser;
import com.findit.joog.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -218275426;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.Meetings</code>.
     */
    public final Meetings MEETINGS = com.findit.joog.tables.Meetings.MEETINGS;

    /**
     * The table <code>public.Meetings_User</code>.
     */
    public final MeetingsUser MEETINGS_USER = com.findit.joog.tables.MeetingsUser.MEETINGS_USER;

    /**
     * The table <code>public.User</code>.
     */
    public final User USER = com.findit.joog.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Meetings.MEETINGS,
            MeetingsUser.MEETINGS_USER,
            User.USER);
    }
}
