/*
 * This file is generated by jOOQ.
*/
package com.findit.joog;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.Meetings_meeting_id_seq</code>
     */
    public static final Sequence<Integer> MEETINGS_MEETING_ID_SEQ = new SequenceImpl<Integer>("Meetings_meeting_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.Student_Meeting_id_seq</code>
     */
    public static final Sequence<Integer> STUDENT_MEETING_ID_SEQ = new SequenceImpl<Integer>("Student_Meeting_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.Students_student_id_seq</code>
     */
    public static final Sequence<Integer> STUDENTS_STUDENT_ID_SEQ = new SequenceImpl<Integer>("Students_student_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
