/*
 * This file is generated by jOOQ.
*/
package com.findit.joog;


import com.findit.joog.tables.Meetings;
import com.findit.joog.tables.MeetingsUser;
import com.findit.joog.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.Meetings</code>.
     */
    public static final Meetings MEETINGS = com.findit.joog.tables.Meetings.MEETINGS;

    /**
     * The table <code>public.Meetings_User</code>.
     */
    public static final MeetingsUser MEETINGS_USER = com.findit.joog.tables.MeetingsUser.MEETINGS_USER;

    /**
     * The table <code>public.User</code>.
     */
    public static final User USER = com.findit.joog.tables.User.USER;
}
